"""add tables

Revision ID: 378dcad90465
Revises: 
Create Date: 2024-12-14 18:23:17.240651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '378dcad90465'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('hostel', sa.String(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('exams_points', sa.Integer(), nullable=False),
    sa.Column('bonus_points', sa.Integer(), nullable=False),
    sa.Column('education', sa.String(), nullable=False),
    sa.Column('study_form', sa.String(), nullable=False),
    sa.Column('reception_form', sa.String(), nullable=False),
    sa.Column('speciality', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personaldatas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('dad_name', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('recomendates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('top_n', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('foreign', sa.String(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('bonus_points', sa.Integer(), nullable=False),
    sa.Column('exams', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('education', sa.String(), nullable=False),
    sa.Column('study_form', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recomendates')
    op.drop_table('personaldatas')
    op.drop_table('classifiers')
    # ### end Alembic commands ###
