"""Create Tables

Revision ID: 5f7f97ca58e8
Revises: 
Create Date: 2024-12-05 18:56:37.819826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7f97ca58e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personaldatas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('dad_name', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('recomendates',
    sa.Column('recomendate_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('hostel', sa.String(), nullable=True),
    sa.Column('gpa', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('exams_points', sa.Integer(), nullable=False),
    sa.Column('bonus_points', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(), nullable=False),
    sa.Column('study_form', sa.String(), nullable=True),
    sa.Column('reception_form', sa.String(), nullable=False),
    sa.Column('speciality', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['recomendate_id'], ['personaldatas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recomendate_id'),
    sa.UniqueConstraint('recomendate_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recomendates')
    op.drop_table('personaldatas')
    # ### end Alembic commands ###
