"""new column

Revision ID: 41d9177bb7f5
Revises: 1d59eb593ef5
Create Date: 2024-12-06 04:50:10.408620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d9177bb7f5'
down_revision: Union[str, None] = '1d59eb593ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personaldatas', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'personaldatas', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personaldatas', type_='unique')
    op.drop_column('personaldatas', 'email')
    # ### end Alembic commands ###
