"""new recomendate

Revision ID: 1d59eb593ef5
Revises: 5f7f97ca58e8
Create Date: 2024-12-05 23:30:35.816725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d59eb593ef5'
down_revision: Union[str, None] = '5f7f97ca58e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'personaldatas', ['id'])
    op.add_column('recomendates', sa.Column('top_n', sa.Integer(), nullable=False))
    op.add_column('recomendates', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('recomendates', sa.Column('sport', sa.String(), nullable=True))
    op.add_column('recomendates', sa.Column('foreign', sa.String(), nullable=False))
    op.add_column('recomendates', sa.Column('total_points', sa.Integer(), nullable=False))
    op.add_column('recomendates', sa.Column('exams', postgresql.ARRAY(sa.String()), nullable=True))
    op.alter_column('recomendates', 'bonus_points',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('recomendates', 'study_form',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'recomendates', ['recomendate_id'])
    op.drop_column('recomendates', 'priority')
    op.drop_column('recomendates', 'exams_points')
    op.drop_column('recomendates', 'hostel')
    op.drop_column('recomendates', 'speciality')
    op.drop_column('recomendates', 'reception_form')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recomendates', sa.Column('reception_form', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('recomendates', sa.Column('speciality', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('recomendates', sa.Column('hostel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recomendates', sa.Column('exams_points', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('recomendates', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recomendates', type_='unique')
    op.alter_column('recomendates', 'study_form',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recomendates', 'bonus_points',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('recomendates', 'exams')
    op.drop_column('recomendates', 'total_points')
    op.drop_column('recomendates', 'foreign')
    op.drop_column('recomendates', 'sport')
    op.drop_column('recomendates', 'age')
    op.drop_column('recomendates', 'top_n')
    op.drop_constraint(None, 'personaldatas', type_='unique')
    # ### end Alembic commands ###
