"""update table

Revision ID: 71e18c9e4283
Revises: cd39b6e93e3a
Create Date: 2025-01-13 00:16:23.539791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e18c9e4283'
down_revision: Union[str, None] = 'cd39b6e93e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('personaldatas_email_key', 'personaldatas', type_='unique')
    op.drop_constraint('personaldatas_id_vk_key', 'personaldatas', type_='unique')
    op.drop_constraint('personaldatas_phone_number_key', 'personaldatas', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('personaldatas_phone_number_key', 'personaldatas', ['phone_number'])
    op.create_unique_constraint('personaldatas_id_vk_key', 'personaldatas', ['id_vk'])
    op.create_unique_constraint('personaldatas_email_key', 'personaldatas', ['email'])
    # ### end Alembic commands ###
